const CATEGORIAS_ALIMENTOS = [
  {
    id: "carnes",
    nome: "Carnes & Proteínas",
    itens: [
      { id: "boi-costela", nome: "Boi - Costela", porcao: "0", carbs: 0, notas: "Alta gordura - preferir" },
      { id: "boi-contrafil", nome: "Boi - Contrafilé", porcao: "0", carbs: 0, notas: "Otimo custo-beneficio" },
      { id: "boi-picanha", nome: "Boi - Picanha", porcao: "0", carbs: 0, notas: "Alta gordura" },
      { id: "boi-patinho", nome: "Boi - Patinho", porcao: "0", carbs: 0, notas: "Magro - adicionar gordura" },
      { id: "boi-moida-8020", nome: "Boi - Moida 80/20", porcao: "0", carbs: 150, notas: "Ideal para dia a dia" },
      { id: "boi-moida-7030", nome: "Boi - Moida 70/30", porcao: "0", carbs: 150, notas: "Mais gordura, mais sabor" },
      { id: "boi-alcatra", nome: "Boi - Alcatra", porcao: "0", carbs: 0, notas: "Versatil" },
      { id: "boi-maminha", nome: "Boi - Maminha", porcao: "0", carbs: 0, notas: "Macia" },
      { id: "boi-coxao-mole", nome: "Boi - Coxao mole", porcao: "0", carbs: 0, notas: "Otima para assar" },
      { id: "boi-figo-de-boi", nome: "Boi - Figo de boi", porcao: "0", carbs: 100, notas: "Powerhouse nutricional - 1x/semana" },
      { id: "boi-coracao", nome: "Boi - Coracao", porcao: "0", carbs: 100, notas: "CoQ10 - 1x/semana" },
      { id: "boi-lingua", nome: "Boi - Lingua", porcao: "0", carbs: 100, notas: "Gordurosa e saborosa" },
      { id: "boi-rim", nome: "Boi - Rim", porcao: "0", carbs: 100, notas: "Rico em selenio" },
      { id: "frango-coxa-c-pele", nome: "Frango - Coxa c/ pele", porcao: "0", carbs: 150, notas: "Mais gordura - preferir" },
      { id: "frango-sobrecoxa", nome: "Frango - Sobrecoxa", porcao: "0", carbs: 150, notas: "Otimo custo" },
      { id: "frango-peito-c-pele", nome: "Frango - Peito c/ pele", porcao: "0", carbs: 150, notas: "Adicionar gordura no preparo" },
      { id: "frango-coracao-de-frango", nome: "Frango - Coracao de frango", porcao: "0", carbs: 100, notas: "Otimo petisco" },
      { id: "porco-barriga", nome: "Porco - Barriga", porcao: "0", carbs: 100, notas: "Alta gordura" },
      { id: "porco-lombo", nome: "Porco - Lombo", porcao: "0", carbs: 150, notas: "Magro - adicionar gordura" },
      { id: "porco-pernil", nome: "Porco - Pernil", porcao: "0", carbs: 150, notas: "Assado lento" },
      { id: "porco-costela", nome: "Porco - Costela", porcao: "0", carbs: 150, notas: "Gordurosa" },
      { id: "porco-bacon-sem-acucar", nome: "Porco - Bacon (sem acucar)", porcao: "0", carbs: 30, notas: "Verificar rotulo - sem acucar adicionado" },
      { id: "linguica", nome: "Linguiça", porcao: "0", carbs: 100, notas: "Verificar rotulo - sem acucar adicionado" },
      { id: "cordeiro-costela", nome: "Cordeiro - Costela", porcao: "0", carbs: 150, notas: "Alta gordura" },
      { id: "cordeiro-carre", nome: "Cordeiro - Carre", porcao: "0", carbs: 150, notas: "Premium" },
      { id: "cordeiro-perna", nome: "Cordeiro - Perna", porcao: "0", carbs: 150, notas: "Otimo assado" },
    ]
  },
  {
    id: "ovos",
    nome: "Ovos",
    itens: [
      { id: "ovo-de-galinha-caipira", nome: "Ovo de galinha caipira", porcao: "0", carbs: 1, notas: "Indice nutricional perfeito" },
      { id: "ovo-de-pata", nome: "Ovo de pata", porcao: "0", carbs: 1, notas: "Maior, mais rico" },
    ]
  },
  {
    id: "peixes",
    nome: "Peixes",
    itens: [
      { id: "salmao-selvagem", nome: "Salmao selvagem", porcao: "0", carbs: 150, notas: "Omega-3, vitamina D" },
      { id: "sardinha-em-conserva", nome: "Sardinha em conserva", porcao: "0", carbs: 1, notas: "Calcio (espinhas), omega-3" },
      { id: "cavala", nome: "Cavala", porcao: "0", carbs: 150, notas: "Alto omega-3" },
      { id: "atum-fresco", nome: "Atum fresco", porcao: "0", carbs: 150, notas: "Limitado por mercurio" },
      { id: "atum-em-conserva-oleo", nome: "Atum em conserva (oleo)", porcao: "0", carbs: 1, notas: "Escorrer o oleo" },
      { id: "bacalhau", nome: "Bacalhau", porcao: "0", carbs: 150, notas: "Dessalgar antes" },
      { id: "merluza", nome: "Merluza", porcao: "0", carbs: 150, notas: "Macia" },
      { id: "cacao", nome: "Cacao", porcao: "0", carbs: 150, notas: "Firme" },
      { id: "tilapia", nome: "Tilapia", porcao: "0", carbs: 150, notas: "Magra - adicionar gordura" },
      { id: "cod-bacalhau-fresco", nome: "Cod (bacalhau fresco)", porcao: "0", carbs: 150, notas: "Macia" },
      { id: "anchova", nome: "Anchova", porcao: "0", carbs: 150, notas: "Sabor intenso" },
    ]
  },
  {
    id: "frutos-do-mar",
    nome: "Frutos do Mar",
    itens: [
      { id: "camaro", nome: "Camarão", porcao: "0", carbs: 150, notas: "Selênio, iodo" },
      { id: "ostras", nome: "Ostras", porcao: "0", carbs: 6, notas: "Zinco (76mg/6 ostras!)" },
      { id: "mariscos", nome: "Mariscos", porcao: "0", carbs: 150, notas: "B12, ferro" },
      { id: "lula", nome: "Lula", porcao: "0", carbs: 150, notas: "Magro" },
      { id: "polvo", nome: "Polvo", porcao: "0", carbs: 150, notas: "Magro" },
    ]
  },
  {
    id: "gorduras",
    nome: "Gorduras & Óleos",
    itens: [
      { id: "azeite-de-oliva-extravirgem", nome: "Azeite de oliva extravirgem", porcao: "0", carbs: 1, notas: "Preferir: saladas e finalizacao" },
      { id: "oleo-de-coco-extravirgem", nome: "Oleo de coco extravirgem", porcao: "0", carbs: 1, notas: "Cozinhar, cafe bulletproof" },
      { id: "manteiga-grassfed-se-possivel", nome: "Manteiga (grass-fed se possivel)", porcao: "0", carbs: 1, notas: "Cozinhar, cafe, finalizar carnes" },
      { id: "ghee-manteiga-clarificada", nome: "Ghee (manteiga clarificada)", porcao: "0", carbs: 1, notas: "Alta temperatura, sem lactose" },
      { id: "banha-porco", nome: "Banha (porco)", porcao: "0", carbs: 1, notas: "Frituras, refogados" },
      { id: "sebo-bovino", nome: "Sebo bovino", porcao: "0", carbs: 1, notas: "Alta temperatura" },
      { id: "natacreme-de-leite-fresco", nome: "Nata/creme de leite fresco", porcao: "0.4", carbs: 2, notas: "Molhos, estrogonofe" },
      { id: "oleo-mct", nome: "Oleo MCT", porcao: "0", carbs: 1, notas: "Energia rápida - comecar com 1/2 dose" },
      { id: "maionese-caseira", nome: "Maionese caseira", porcao: "0", carbs: 1, notas: "Ovo + oleo + limao + mostarda" },
      { id: "toucinho", nome: "Toucinho", porcao: "0", carbs: 30, notas: "Petisco" },
    ]
  },
  {
    id: "laticinios",
    nome: "Laticínios",
    itens: [
      { id: "queijo-parmesao-ralado", nome: "Queijo parmesao ralado", porcao: "0", carbs: 30, notas: "Otimo para finalizar" },
      { id: "queijo-cheddar", nome: "Queijo cheddar", porcao: "0.5", carbs: 30 },
      { id: "queijo-muarela", nome: "Queijo muçarela", porcao: "1", carbs: 30 },
      { id: "queijo-brie", nome: "Queijo brie", porcao: "0", carbs: 30, notas: "Gorduroso, cremoso" },
      { id: "queijo-gouda", nome: "Queijo gouda", porcao: "0.5", carbs: 30 },
      { id: "queijo-suico", nome: "Queijo suico", porcao: "1.5", carbs: 30 },
      { id: "queijo-provolone", nome: "Queijo provolone", porcao: "0.5", carbs: 30 },
      { id: "queijo-azul-gorgonzola", nome: "Queijo azul (gorgonzola)", porcao: "1.5", carbs: 30 },
      { id: "cream-cheese", nome: "Cream cheese", porcao: "1", carbs: 30, notas: "Versatil" },
      { id: "requeijao-sem-aditivos", nome: "Requeijao (sem aditivos)", porcao: "1", carbs: 30, notas: "Verificar rotulo" },
      { id: "nata", nome: "Nata", porcao: "0.5", carbs: 30 },
      { id: "coalhada-seca", nome: "Coalhada seca", porcao: "2", carbs: 100, notas: "Proteina, probioticos" },
      { id: "iogurte-grego-natural-integral", nome: "Iogurte grego natural integral", porcao: "4", carbs: 100, notas: "Taxa de lactose moderada" },
      { id: "creme-de-leite-lata", nome: "Creme de leite (lata)", porcao: "0.4", carbs: 15, notas: "Sem soro - usar a parte consistente" },
      { id: "ricota", nome: "Ricota", porcao: "4", carbs: 100, notas: "Leve" },
      { id: "cottage-integral", nome: "Cottage (integral)", porcao: "3.5", carbs: 100, notas: "Moderado" },
    ]
  },
  {
    id: "vegetais",
    nome: "Vegetais",
    itens: [
      { id: "espinafre", nome: "Espinafre", porcao: "1", carbs: 1, notas: "Ilimitado" },
      { id: "couve", nome: "Couve", porcao: "2", carbs: 1, notas: "Ilimitado" },
      { id: "alface", nome: "Alface", porcao: "1", carbs: 1, notas: "Ilimitado" },
      { id: "rucula", nome: "Rucula", porcao: "0.5", carbs: 1, notas: "Ilimitado" },
      { id: "agrao", nome: "Agrao", porcao: "0.5", carbs: 1, notas: "Ilimitado" },
      { id: "brocolis", nome: "Brocolis", porcao: "4", carbs: 1, notas: "1-2 xicaras/dia" },
      { id: "couveflor", nome: "Couve-flor", porcao: "3", carbs: 1, notas: "Base para arroz, pure" },
      { id: "abobrinha", nome: "Abobrinha", porcao: "2", carbs: 1, notas: "Espaguete de abobrinha" },
      { id: "aspargos", nome: "Aspargos", porcao: "2", carbs: 6 },
      { id: "pepino", nome: "Pepino", porcao: "2", carbs: 1 },
      { id: "pimentao-vermelho", nome: "Pimentao vermelho", porcao: "4", carbs: 1 },
      { id: "pimentao-verde", nome: "Pimentao verde", porcao: "3", carbs: 1 },
      { id: "cogumelos", nome: "Cogumelos", porcao: "2", carbs: 1 },
      { id: "berinjela", nome: "Berinjela", porcao: "2", carbs: 1 },
      { id: "vagem", nome: "Vagem", porcao: "2", carbs: 1 },
      { id: "couvedebruxelas", nome: "Couve-de-bruxelas", porcao: "5", carbs: 1 },
      { id: "repolho", nome: "Repolho", porcao: "3", carbs: 1 },
      { id: "aiposalsao", nome: "Aipo/salsao", porcao: "2", carbs: 2 },
      { id: "cebola", nome: "Cebola", porcao: "3", carbs: 1, notas: "Usar com moderacao" },
      { id: "tomate", nome: "Tomate", porcao: "3", carbs: 1 },
      { id: "alho", nome: "Alho", porcao: "0.5", carbs: 1, notas: "Usar a vontade" },
      { id: "gengibre", nome: "Gengibre", porcao: "1", carbs: 1, notas: "Usar a vontade" },
      { id: "salsinha", nome: "Salsinha", porcao: "0", carbs: 1, notas: "Usar a vontade" },
      { id: "cebolinha", nome: "Cebolinha", porcao: "0", carbs: 1, notas: "Usar a vontade" },
      { id: "coentro", nome: "Coentro", porcao: "0", carbs: 1, notas: "Usar a vontade" },
      { id: "hortalela", nome: "Hortalela", porcao: "0", carbs: 1, notas: "Usar a vontade" },
      { id: "manjericao", nome: "Manjericao", porcao: "0", carbs: 5, notas: "Usar a vontade" },
      { id: "alecrim", nome: "Alecrim", porcao: "0", carbs: 1, notas: "Usar a vontade" },
      { id: "tomilho", nome: "Tomilho", porcao: "0", carbs: 1, notas: "Usar a vontade" },
      { id: "oregano", nome: "Oregano", porcao: "0", carbs: 1, notas: "Usar a vontade" },
      { id: "cebola-roxa", nome: "Cebola roxa", porcao: "2", carbs: 1, notas: "Moderado" },
    ]
  },
  {
    id: "frutas",
    nome: "Frutas",
    itens: [
      { id: "abacate", nome: "Abacate", porcao: "2", carbs: 1, notas: "Gordura monoinsaturada" },
      { id: "morango", nome: "Morango", porcao: "6", carbs: 5, notas: "Em moderacao" },
      { id: "framboesa", nome: "Framboesa", porcao: "5", carbs: 1, notas: "Em moderacao" },
      { id: "amora", nome: "Amora", porcao: "5", carbs: 1, notas: "Em moderacao" },
      { id: "mirtilo", nome: "Mirtilo", porcao: "5", carbs: 1, notas: "Em moderacao" },
      { id: "limao-sucoraspas", nome: "Limao (suco/raspas)", porcao: "0", carbs: 1, notas: "Usar a vontade" },
      { id: "coco-polpa", nome: "Coco (polpa)", porcao: "2", carbs: 30 },
      { id: "coco-leite", nome: "Coco (leite)", porcao: "2", carbs: 100, notas: "Enlatado integral" },
      { id: "coco-farinha", nome: "Coco (farinha)", porcao: "4", carbs: 30, notas: "Baixo carb, rico em fibras" },
    ]
  },
  {
    id: "oleaginosas",
    nome: "Oleaginosas",
    itens: [
      { id: "macadamia", nome: "Macadamia", porcao: "1.5", carbs: 30, notas: "Menor carb das castanhas" },
      { id: "nozes", nome: "Nozes", porcao: "2", carbs: 30, notas: "Omega-3" },
      { id: "amendoas", nome: "Amendoas", porcao: "3", carbs: 30, notas: "Versatil" },
      { id: "peca", nome: "Peca", porcao: "1", carbs: 30, notas: "Sabor adocicado" },
      { id: "castanhadopara", nome: "Castanha-do-para", porcao: "1.5", carbs: 30, notas: "Rica em selenio" },
      { id: "avela", nome: "Avela", porcao: "2", carbs: 30 },
      { id: "pinoli", nome: "Pinoli", porcao: "3", carbs: 30 },
      { id: "amendoim", nome: "Amendoim", porcao: "4.7", carbs: 30, notas: "Legalmente e leguminosa - moderado" },
    ]
  },
  {
    id: "sementes",
    nome: "Sementes",
    itens: [
      { id: "semente-de-abobora", nome: "Semente de abobora", porcao: "3", carbs: 30, notas: "Zinco, magnesio" },
      { id: "chia", nome: "Chia", porcao: "2", carbs: 30, notas: "Fibra, omega-3" },
      { id: "linhaa-dourada", nome: "Linhaça dourada", porcao: "0", carbs: 30, notas: "Fibra - moida absorve melhor" },
      { id: "gergelim", nome: "Gergelim", porcao: "2", carbs: 30, notas: "Calcio" },
      { id: "girassol", nome: "Girassol", porcao: "3", carbs: 30, notas: "Vitamina E" },
    ]
  },
  {
    id: "farinhas-lowcarb",
    nome: "Farinhas Low-Carb",
    itens: [
      { id: "farinha-de-amendoas", nome: "Farinha de amendoas", porcao: "2", carbs: 30, notas: "Base para paes e tortas" },
      { id: "farinha-de-coco", nome: "Farinha de coco", porcao: "2", carbs: 30, notas: "Absorve muita agua" },
      { id: "farinha-de-linhaa", nome: "Farinha de linhaça", porcao: "0", carbs: 30, notas: "Substituto de ovo vegan" },
      { id: "cacau-em-po-sem-acucar", nome: "Cacau em po (sem acucar)", porcao: "3", carbs: 30, notas: "Chocolate amargo" },
      { id: "psyllium", nome: "Psyllium", porcao: "0", carbs: 10, notas: "Fibra - essencial em keto" },
      { id: "xantana", nome: "Xantana", porcao: "0", carbs: 5, notas: "Espessante" },
      { id: "gelatina-em-po", nome: "Gelatina em po", porcao: "0", carbs: 10, notas: "Colageno" },
      { id: "proteina-do-soro-whey-sem-sabor", nome: "Proteina do soro (whey) sem sabor", porcao: "0", carbs: 30, notas: "Suplementar se necessario" },
      { id: "proteina-colageno", nome: "Proteina colageno", porcao: "0", carbs: 30, notas: "Pele, juntas" },
      { id: "torresmo-moido-farinha-de-torresmo", nome: "Torresmo moido (farinha de torresmo)", porcao: "0", carbs: 30, notas: "Empanados keto" },
    ]
  },
  {
    id: "condimentostemperos",
    nome: "Condimentos & Temperos",
    itens: [
      { id: "sal-marinho", nome: "Sal marinho", porcao: "0", carbs: 0, notas: "Essencial - usar liberalmente" },
      { id: "sal-rosa-do-himalaia", nome: "Sal rosa do Himalaia", porcao: "0", carbs: 0, notas: "Minerais adicionais" },
      { id: "pimentadoreino-moida-na-hora", nome: "Pimenta-do-reino moida na hora", porcao: "0", carbs: 0 },
      { id: "paprica-doce", nome: "Paprica doce", porcao: "0", carbs: 1 },
      { id: "paprica-defumada", nome: "Paprica defumada", porcao: "0", carbs: 1 },
      { id: "curry-em-po", nome: "Curry em po", porcao: "0", carbs: 1 },
      { id: "cucurma-acafrao-da-terra", nome: "Cucurma (acafrao da terra)", porcao: "0", carbs: 1, notas: "Anti-inflamatoria" },
      { id: "cominho", nome: "Cominho", porcao: "0", carbs: 1 },
      { id: "canela-em-po", nome: "Canela em po", porcao: "0", carbs: 1, notas: "Cafe, receitas" },
      { id: "nozmoscada", nome: "Noz-moscada", porcao: "0", carbs: 1 },
      { id: "cravo", nome: "Cravo", porcao: "0", carbs: 1 },
      { id: "pimenta-calabresa", nome: "Pimenta calabresa", porcao: "0", carbs: 1 },
      { id: "mostarda-amarela", nome: "Mostarda amarela", porcao: "0", carbs: 1 },
      { id: "mostarda-dijon", nome: "Mostarda dijon", porcao: "0", carbs: 1 },
      { id: "vinagre-de-maca", nome: "Vinagre de maca", porcao: "0", carbs: 1 },
      { id: "vinagre-de-vinho-tinto", nome: "Vinagre de vinho tinto", porcao: "0", carbs: 1 },
      { id: "molho-de-soja-shoyu", nome: "Molho de soja (shoyu)", porcao: "1", carbs: 1, notas: "Contem glutamato natural" },
      { id: "molho-ingles", nome: "Molho ingles", porcao: "0.5", carbs: 1 },
      { id: "extrato-de-baunilha", nome: "Extrato de baunilha", porcao: "0", carbs: 1 },
      { id: "pasta-de-alho", nome: "Pasta de alho", porcao: "0", carbs: 1 },
    ]
  },
  {
    id: "adocantes",
    nome: "Adoçantes",
    itens: [
      { id: "stevia-liquida", nome: "Stevia liquida", porcao: "0", carbs: 0, notas: "Natural - preferir liquida" },
      { id: "eritritol", nome: "Eritritol", porcao: "0", carbs: 1, notas: "Zero caloria, G.I. zero" },
      { id: "xilitol", nome: "Xilitol", porcao: "2", carbs: 1, notas: "G.I. baixo - toxico para caes" },
      { id: "monk-fruit-fruta-do-monge", nome: "Monk fruit (fruta do monge)", porcao: "0", carbs: 0, notas: "Natural" },
      { id: "alulose", nome: "Alulose", porcao: "0", carbs: 1, notas: "Emergente - pouco processado" },
    ]
  },
  {
    id: "bebidas",
    nome: "Bebidas",
    itens: [
      { id: "agua-filtradamineral", nome: "Agua filtrada/mineral", porcao: "0", carbs: 0, notas: "Fonte principal - 2-3L/dia" },
      { id: "agua-com-gas", nome: "Agua com gas", porcao: "0", carbs: 0 },
      { id: "cafe-preto-coado", nome: "Cafe preto coado", porcao: "0", carbs: 0, notas: "Sem acucar" },
      { id: "cafe-espresso", nome: "Cafe espresso", porcao: "0", carbs: 0 },
      { id: "cha-verde", nome: "Cha verde", porcao: "0", carbs: 0, notas: "Antioxidantes" },
      { id: "cha-preto", nome: "Cha preto", porcao: "0", carbs: 0 },
      { id: "cha-de-ervas-hortela-camomila-etc", nome: "Cha de ervas (hortela, camomila, etc)", porcao: "0", carbs: 0 },
      { id: "agua-aromatizada-limao-hortela", nome: "Agua aromatizada (limao + hortela)", porcao: "0", carbs: 0 },
      { id: "caldo-de-ossos-bone-broth", nome: "Caldo de ossos (bone broth)", porcao: "0", carbs: 1, notas: "Colageno, eletrolitos - caseiro" },
    ]
  },
  {
    id: "snacks-keto",
    nome: "Snacks Keto",
    itens: [
      { id: "torresmo-pururuca", nome: "Torresmo (pururuca)", porcao: "0", carbs: 50, notas: "Crocante - substitui batata frita" },
      { id: "chips-de-couve", nome: "Chips de couve", porcao: "2", carbs: 50, notas: "Caseiro: couve + azeite + forno" },
      { id: "chips-de-queijo-parmesao-assado", nome: "Chips de queijo (parmesao assado)", porcao: "0.5", carbs: 30, notas: "Forno 180° ate dourar" },
      { id: "azeitonas-verdepreta", nome: "Azeitonas (verde/preta)", porcao: "1", carbs: 50, notas: "Gordura monoinsaturada" },
      { id: "pepino-em-palitos", nome: "Pepino em palitos", porcao: "2", carbs: 100, notas: "Com cream cheese" },
      { id: "salsicha-sem-acucaramido", nome: "Salsicha (sem acucar/amido)", porcao: "0", carbs: 2, notas: "Verificar rotulo" },
      { id: "ovo-de-codorna", nome: "Ovo de codorna", porcao: "0", carbs: 5, notas: "Petisco rapido" },
      { id: "picles-sem-acucar", nome: "Picles (sem acucar)", porcao: "1", carbs: 50, notas: "Probiótico natural" },
    ]
  },
];
